# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
      with:
        ruby-version: 2.7
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gem-deps-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-deps-
    - name: Install dependencies
      run: |
        bundle config path vendor/bundle
        bundle install
    - name: Run tests
      run: bundle exec rake
    - uses: actions/cache@v2
      with:
        path: example/vendor/bundle
        key: ${{ runner.os }}-example-deps-${{ hashFiles('example/**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-example-deps-
    - name: Install example dependencies for example
      working-directory: example
      run: |
        bundle config path vendor/bundle
        bundle install
    - name: Run specs for example
      working-directory: example
      run: rake
